version: '2'
services:
  sut:
    image: tutum/curl
    links:
      - web:webapi
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ci-webapi
    container_name: ci-webapi
    ports:
      - "80:5000"